[package]
name = "vxug-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.15", features = ["blocking"] }
tokio = {version = "1.45.0", features = ["full"] }
regex = "1.11.1"
scraper = "0.23.1"
futures = "0.3.31"
indicatif = "0.17"
